// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0eV0iZYK02IsAl4Tx_Ks15YYypsoyF-0',
    appId: '1:742098792107:web:9a34b8804827f21fba11ee',
    messagingSenderId: '742098792107',
    projectId: 'retoredom8',
    authDomain: 'retoredom8.firebaseapp.com',
    storageBucket: 'retoredom8.appspot.com',
    measurementId: 'G-DD8BBBMQ87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDluLR-VxmekVN8d3IBYzk5BNFyBvjF0ks',
    appId: '1:742098792107:android:33e4f4ce63055dc6ba11ee',
    messagingSenderId: '742098792107',
    projectId: 'retoredom8',
    storageBucket: 'retoredom8.appspot.com',
  );
}
